name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install backend dependencies
        working-directory: backend
        run: pip install -r ./requirements.txt
      - name: Run pylint
        run: pylint backend --rcfile=.pylintrc
      - name: run pytest
        working-directory: backend
        run: coverage run --branch -m pytest

