name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install backend dependencies
        working-directory: backend
        run: pip install -r ./requirements.txt
      - name: Run pylint
        working-directory: backend
        run: pylint src --rcfile=.pylintrc
      - name: run pytest
        working-directory: backend
        run: coverage run --branch -m pytest
      - name: Coverage report
        working-directory: backend
        run: coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: install frontend dependencies
        working-directory: frontend
        run: npm ci
      - name: frontend tests
        working-directory: frontend
        run: CI=true npm test
      - name: run eslint
        working-directory: frontend
        run: npx eslint --fix --ext .js,.jsx .
        

